services:
  php_a:
    image: ghcr.io/benedeczkin/dateapp-app-a:${APP_TAG}
    ports:
      - "127.0.0.1:9001:9000"
    environment:
      TZ: Europe/Budapest
      REDIS_HOST: redis
      REDIS_PORT: "${REDIS_PORT}"
      REDIS_PASS: "${REDIS_PASS}"
      REDIS_DB: "${REDIS_DB}"
    depends_on:
      - redis
    restart: unless-stopped

  php_b:
    image: ghcr.io/benedeczkin/dateapp-app-b:${APP_TAG}
    ports:
      - "127.0.0.1:9002:9000"
    environment:
      TZ: Europe/Budapest
      REDIS_HOST: redis
      REDIS_PORT: "${REDIS_PORT}"
      REDIS_PASS: "${REDIS_PASS}"
      REDIS_DB: "${REDIS_DB}"
    depends_on:
      - redis
    restart: unless-stopped

  cron:
    image: ghcr.io/benedeczkin/dateapp-app-a:${APP_TAG}
    command: ["crond","-f","-l","2"]
    environment:
      TZ: Europe/Budapest
      REDIS_HOST: redis
      REDIS_PORT: "${REDIS_PORT}"
      REDIS_PASS: "${REDIS_PASS}"
      REDIS_DB: "${REDIS_DB}"
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    command: >
      redis-server
      --appendonly yes
      --requirepass ${REDIS_PASS}
      --databases 16
      --save 900 1 --save 300 10 --save 60 10000
      --maxmemory-policy noeviction
    environment:
      REDIS_PASS: "${REDIS_PASS}"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASS}", "PING"]
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  redis-data:
