services:
  nginx:
    image: nginx:1.27-alpine
    ports: ["80:80"]
    depends_on:
      php_a: { condition: service_started }
      php_b: { condition: service_started }
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL","wget -qO- http://127.0.0.1:8081/health || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s

  php_a:
    image: ghcr.io/benedeczkin/dateapp-app-a:${APP_TAG}
    restart: unless-stopped

  php_b:
    image: ghcr.io/benedeczkin/dateapp-app-b:${APP_TAG}
    restart: unless-stopped
